### ISSUE TITLE
'ClientAuth' is not defined

### ISSUE THREAD

**Issue by n3xus** [02strich/django-auth-kerberos#13]
I'm receiving following error

```
    Traceback (most recent call last):
    
    File "C:\Python35\lib\site-packages\django_auth_kerberos\backends.py", line 61, in check_password
        kerberos.checkPassword(username.lower(), password, getattr(settings, "KRB5_SERVICE", ""), getattr(settings, "KRB5_REALM", ""))
    
      File "C:\Python35\lib\site-packages\kerberos_sspi.py", line 98, in checkPassword
        ca = ClientAuth("Kerberos", auth_info = auth_info, targetspn=service)
    
    NameError: name 'ClientAuth' is not defined
```

**Comment by 02strich** [comment]
It looks like your kerberos installation is broken. Which kerberos package did you install including which version?

Sent from my iPhone

On Mar 20, 2018, at 02:19, n3xus <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm receiving following error

    Traceback (most recent call last):

    File "C:\Python35\lib\site-packages\django_auth_kerberos\backends.py", line 61, in check_password
        kerberos.checkPassword(username.lower(), password, getattr(settings, "KRB5_SERVICE", ""), getattr(settings, "KRB5_REALM", ""))

      File "C:\Python35\lib\site-packages\kerberos_sspi.py", line 98, in checkPassword
        ca = ClientAuth("Kerberos", auth_info = auth_info, targetspn=service)

    NameError: name 'ClientAuth' is not defined
